<a href="https://colab.research.google.com/github/RamziRBM/lab-numpy-en/blob/master/your-code/main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [5]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [6]:
### [your code here]
print(np.__version__)
np.show_config()

2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [7]:
### [your code here]
a = np.random.random((2,3,5))


### 4. Print a.


In [8]:
### [your code here]
print(a)

[[[0.89131707 0.76104232 0.52940857 0.78380383 0.1906251 ]
  [0.78322395 0.64416189 0.37306088 0.76837671 0.90036614]
  [0.05315942 0.41544365 0.92323923 0.18716029 0.50418908]]

 [[0.48491674 0.08197636 0.86114708 0.990174   0.23944264]
  [0.67846658 0.4328654  0.59391098 0.69520768 0.82895333]
  [0.37286658 0.51163247 0.35094493 0.90597783 0.9327716 ]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [9]:
### [your code here]
b = np.random.random((5,2,3))


### 6. Print b.


In [10]:
### [your code here]
print(b)

[[[0.66741459 0.68944338 0.9884298 ]
  [0.53735516 0.6097643  0.81651546]]

 [[0.16858255 0.14883387 0.35874643]
  [0.25997366 0.2409852  0.82698715]]

 [[0.46042956 0.99786078 0.46161801]
  [0.2022966  0.31046324 0.55017465]]

 [[0.69010526 0.52541168 0.92007607]
  [0.93143066 0.57376991 0.40184366]]

 [[0.62370529 0.29730033 0.25420492]
  [0.00144057 0.21754384 0.13134678]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [11]:
### [your code here]


len_a=len(a)*len(a[0])*len(a[0][0])
len_b=len(b)*len(b[0])*len(b[0][0])
print(len_a,len_b)



30 30



### 8. Are you able to add a and b? Why or why not?


In [12]:
### [your code here]
np.add(a,b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [13]:
### [your code here]
c=np.transpose(b, axes=(1,2,0))
print(c)

[[[0.66741459 0.16858255 0.46042956 0.69010526 0.62370529]
  [0.68944338 0.14883387 0.99786078 0.52541168 0.29730033]
  [0.9884298  0.35874643 0.46161801 0.92007607 0.25420492]]

 [[0.53735516 0.25997366 0.2022966  0.93143066 0.00144057]
  [0.6097643  0.2409852  0.31046324 0.57376991 0.21754384]
  [0.81651546 0.82698715 0.55017465 0.40184366 0.13134678]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [14]:
### [your code here]
d=np.add(a,c)


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [15]:
### [your code here]
print(a)
print(d)


[[[0.89131707 0.76104232 0.52940857 0.78380383 0.1906251 ]
  [0.78322395 0.64416189 0.37306088 0.76837671 0.90036614]
  [0.05315942 0.41544365 0.92323923 0.18716029 0.50418908]]

 [[0.48491674 0.08197636 0.86114708 0.990174   0.23944264]
  [0.67846658 0.4328654  0.59391098 0.69520768 0.82895333]
  [0.37286658 0.51163247 0.35094493 0.90597783 0.9327716 ]]]
[[[1.55873166 0.92962487 0.98983813 1.47390909 0.8143304 ]
  [1.47266733 0.79299577 1.37092166 1.29378838 1.19766647]
  [1.04158922 0.77419008 1.38485724 1.10723636 0.758394  ]]

 [[1.0222719  0.34195001 1.06344368 1.92160466 0.24088322]
  [1.28823088 0.67385059 0.90437423 1.26897758 1.04649716]
  [1.18938204 1.33861962 0.90111958 1.3078215  1.06411838]]]



### 12. Multiply a and c. Assign the result to e.


In [16]:
### [your code here]
e=np.multiply(a,c)



### 13. Does e equal to a? Why or why not?


In [17]:
### [your code here]

np.equal(a,e)

array([[[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],

       [[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]]])



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [18]:
### [your code here]



d_max=np.max(d)
d_min=np.min(d)
d_mean=np.mean(d)




### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [19]:
### [your code here]


f=np.empty((2,3,5))
print(f)



[[[1.55873166 0.92962487 0.98983813 1.47390909 0.8143304 ]
  [1.47266733 0.79299577 1.37092166 1.29378838 1.19766647]
  [1.04158922 0.77419008 1.38485724 1.10723636 0.758394  ]]

 [[1.0222719  0.34195001 1.06344368 1.92160466 0.24088322]
  [1.28823088 0.67385059 0.90437423 1.26897758 1.04649716]
  [1.18938204 1.33861962 0.90111958 1.3078215  1.06411838]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [20]:
### [your code here]


for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            d_val=d[i,j,k]
            if d_val>d_mean and d_val<d_max:
                f[i,j,k]=75
            elif d_val==d_mean:
                f[i,j,k]=50
            elif d_val==d_min:
                f[i,j,k]=0
            elif d_val==d_max:
                f[i,j,k]=100
            else:
                f[i,j,k]=0







### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [21]:
### [your code here]
print(d)
print(f)


[[[1.55873166 0.92962487 0.98983813 1.47390909 0.8143304 ]
  [1.47266733 0.79299577 1.37092166 1.29378838 1.19766647]
  [1.04158922 0.77419008 1.38485724 1.10723636 0.758394  ]]

 [[1.0222719  0.34195001 1.06344368 1.92160466 0.24088322]
  [1.28823088 0.67385059 0.90437423 1.26897758 1.04649716]
  [1.18938204 1.33861962 0.90111958 1.3078215  1.06411838]]]
[[[ 75.   0.   0.  75.   0.]
  [ 75.   0.  75.  75.  75.]
  [  0.   0.  75.  75.   0.]]

 [[  0.   0.   0. 100.   0.]
  [ 75.   0.   0.  75.   0.]
  [ 75.  75.   0.  75.   0.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [22]:
### [your code here]


f=f.astype(object)
for i in range(f.shape[0]):
    for j in range(f.shape[1]):
        for k in range(f.shape[2]):
            f_val=f[i,j,k]
            if f_val==0:
                f[i,j,k]="A"
            elif f_val==25:
                f[i,j,k]="B"
            elif f_val==50:
                f[i,j,k]="C"
            elif f_val==75:
                f[i,j,k]="D"
            else:
                f[i,j,k]="E"

print(f)



[[['D' 'A' 'A' 'D' 'A']
  ['D' 'A' 'D' 'D' 'D']
  ['A' 'A' 'D' 'D' 'A']]

 [['A' 'A' 'A' 'E' 'A']
  ['D' 'A' 'A' 'D' 'A']
  ['D' 'D' 'A' 'D' 'A']]]
